global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-netapp-ontapcloud-sql
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-netapp-ontapcloud-sqlt1:
    parameter_input: netapp-otc-sql-master-parameter.json
    template_file: netapp-otc-sql-master.template
  quickstart-netapp-ontapcloud-sqlt2:
    parameter_input: netapp-otc-sql-master-parameter.json
    template_file: netapp-otc-sqlserver.template
